#!/usr/bin/env python3
"""Generate model-only FK/IK evidence and render poses. Never opens hardware ports.

    python tools/build_control_poses.py --model-dir models/so101 --output control-poses.json

The output feeds the website's illustration renderer; copy it there by hand.
"""
import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np

# Imports the published IK program; keep generated bytecode out of the tree.
sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "IK/so101_cartesian_demo.py"
# Exaggerated model-only displacement for a legible before/after illustration.
ILLUSTRATION_DELTA_MM = (0.0, 0.0, 30.0)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location("cartesian_demo", DEMO)
    demo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(demo)
    kinematics, limits = demo.load_kinematics(args.model_dir)
    start = np.asarray(demo.PREVIEW_JOINTS_DEG)
    xyz = kinematics.forward_kinematics(start)[:3, 3].copy()
    target = xyz + np.asarray(ILLUSTRATION_DELTA_MM) / 1000
    solved, actual, residual = demo.solve_position(kinematics, start, target, limits)
    result = {"modelCommit": demo.MODEL_COMMIT, "lerobotVersion": demo.LEROBOT_VERSION,
        "hardwareEvidence": False, "jointNames": demo.JOINTS,
        "targetFrame": "gripper_frame_link", "deltaMm": ILLUSTRATION_DELTA_MM,
        "positionErrorMm": residual, "targetXyzM": target.tolist(),
        "poses": [{"name": "ik-before", "degrees": start.tolist(), "xyzM": xyz.tolist()},
                  {"name": "ik-after", "degrees": solved.tolist(), "xyzM": actual.tolist()}]}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
